Feature/update inscricao
estartando-devs/inscricao pull request #40
Opened 2022-01-29 03:49 UTC by joaoprferreira

Fala pessoal, podem validar por favor esse pull request, se trata de algumas atualizações para inscrições desse ano

2022-02-01 03:34 UTC, jonataspinto approved these changes
Valeu @joaoprferreira! Só não faz o merge beleza?!

@alanaraujop @Brenont @yagovaluchedevs

2022-02-01 12:28 UTC, estartandodevs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Inscrição](https://trello.com/c/STucV1gV/1-inscri%C3%A7%C3%A3o)

2022-02-14 15:32 UTC, jonataspinto approved these changes

2022-02-14 15:33 UTC, jonataspinto commented
> @joaoprferreira  @jonataspinto  esse mr ainda faz sentido?

Faz sim, pode dar sua revisão? Vou incluir apenas um job aqui.

2022-02-14 16:13 UTC, ramonxm requested changes

2022-02-14 16:13 UTC, ramonxm commented on src/services/student.service.ts
> +        content: `Mais um inscrito no Estartando Devs 2022 🎉
Aqui pode ser um new Date().getFullYear() tbm

2022-02-14 17:58 UTC, merged